# Generated by Django 5.0.7 on 2024-07-21 16:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("indiascope_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="form",
            name="message",
            field=models.CharField(max_length=1000),
        ),
    ]
